on:
    schedule:
      - cron: '0 * * * *'
    push:
      branches: main
name: Scrape Jobs
jobs:
    render:
      name: Scrape Jobs
      runs-on: macOS-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: Scrape data and send email
          run: python3 send.py
          env:
            GMAIL_PWD: ${{ secrets.GMAIL_PWD }}
        - name: Update new data
          run: |
            git add '*.json'
            git commit -m "Update data" || echo "No changes to commit"
            git push origin main || echo "No changes to push"

              